version: '3.7'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - default:/data/db
    networks:
      default:
        aliases:
          - graphik
networks:
  default:

volumes:
  default: